<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DataViewer.UI.Avalonia</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Templates\FieldTemplates.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Templates\FieldTemplates.axaml.cs">
      <DependentUpon>FieldTemplates.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\PropertiesView.axaml.cs">
      <DependentUpon>PropertiesView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\TableContentView.axaml.cs">
      <DependentUpon>TableContentView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\TablesView.axaml.cs">
      <DependentUpon>TablesView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\DataBasesView.axaml.cs">
      <DependentUpon>DatabasesView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
